routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/register', function (){
   return redirect('/login');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function(){
    Route::resource('students', 'StudentController');
    Route::resource('authorities', 'AuthorityController');
    Route::resource('notices', 'NoticeController');
    Route::resource('batches', 'BatchController');
});

app/Notice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notice extends Model
{
    protected $fillable = ['batch_id', 'type', 'priority', 'title', 'content', 'attachment', 'status'];

    const TYPE_CLASS = 'class';
    const TYPE_EXAM = 'exam';
    const TYPE_OTHERS = 'others';

    public function scopeCurrentBatch()
    {

    }

    public function batch()
    {
        return $this->belongsTo(Batch::class);
    }
}

app/Http/Controllers/AuthorityController.php
<?php

namespace App\Http\Controllers;

use App\Batch;
use App\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

class AuthorityController extends Controller
{
    const IMAGE_PATH = 'public/students/';
    const VIEW_PATH = 'authority.authorities.';

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $authorities = User::where('role', '!=', User::ROLE_STUDENT)->get();

        return view(self::VIEW_PATH.'index', compact('authorities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $batches = Batch::where('status', 1)->latest()->get();

        $authority = new User();

        $this->authorize('viewAny', $authority);

        $roles = [
          User::ROLE_CR => 'CR',
          User::ROLE_TEACHER => 'Teacher',
          User::ROLE_STAFF => 'Staff',
        ];

        return view(self::VIEW_PATH.'edit', compact('batches', 'authority', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $input = $request->except('_token');

        $this->validator($input)->validate();

        try {
            DB::beginTransaction();
            $input['image'] = md5(microtime()).'.'.$request->file('image')->extension();
            $input['password'] = Hash::make(strlen($input['password']) ? $input['password'] : '123456');

            $authority = User::create($input);

            Storage::putFileAs(
                self::IMAGE_PATH,
                $request->file('image'),
                $authority->image
            );
            DB::commit();

        } catch (\Throwable $exception) {
            Log::debug($exception->getMessage());
            DB::rollBack();
            return back()
                ->with(["error" => "Something Wrong. Please Try Again"])
                ->withInput();
        }

        return back()->with(["success" => "Authority Successfully Created"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Factory|View
     * @throws \Exception
     */
    public function show($id)
    {
        $authority = User::findOrFail($id);

        $this->authorize('viewAny', $authority);

        return view(self::VIEW_PATH.'view', compact('authority'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Factory|View
     * @throws \Exception
     */
    public function edit($id)
    {
        $authority = User::findOrFail($id);

        $this->authorize('viewAny', $authority);

        $batches = Batch::where('status', 1)->latest()->get();

        $roles = [
            User::ROLE_CR => 'CR',
            User::ROLE_TEACHER => 'Teacher',
            User::ROLE_STAFF => 'Staff',
        ];

        return view(self::VIEW_PATH.'edit', compact('authority', 'batches', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(Request $request, $id)
    {
        $authority = User::findOrFail($id);

        $input = $request->except('_token');

        $this->validator($input, $id)->validate();

        try {
            DB::beginTransaction();

            if (strlen($request->post('password'))) {
                $input['password'] = Hash::make($input['password']);
            } else {
                unset($input['password']);
            }

            if ($request->hasFile('image')) {
                $input['image'] = md5(microtime()).'.'.$request->file('image')->extension();

                if ($authority->image && Storage::exists(self::IMAGE_PATH.$authority->image)) {
                    Storage::delete(self::IMAGE_PATH.$authority->image);
                }

                Storage::putFileAs(
                    self::IMAGE_PATH,
                    $request->file('image'),
                    $input['image']
                );
            }
            if ($request->has('image_status') && $request->post('image_status') < 1) {
                $input['image'] = null;
                Storage::delete(self::IMAGE_PATH.$authority->image);
            }

            $authority->update($input);

            DB::commit();
        } catch (\Throwable $exception) {
            Log::debug($exception->getMessage());
            DB::rollBack();
            return back()
                ->with(["error" => "Something Wrong. Please Try Again"])
                ->withInput();
        }

        return back()->with(["success" => "Authority Successfully Updated"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $authority = User::findOrFail($id);

        $this->authorize('viewAny', $authority);

        try {
            if ($authority->image && Storage::exists(self::IMAGE_PATH.$authority->image)) {
                Storage::delete(self::IMAGE_PATH.$authority->image);
            }
            $authority->delete();
        } catch (\Throwable $exception) {
            return redirect()->route('admin.authorities.index')
                ->with(["error" => "Something Wrong. Please Try Again"]);
        }
        return redirect()->route('admin.authorities.index')
            ->with(["success" => "Authority Successfully Created"]);
    }

    public function validator(array $data, $id = null)
    {
        $rule = [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,'.$id],
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            "gender" => "required",
            "role" => "required"
        ];
        return Validator::make($data, $rule, []);
    }
}

app/Http/Controllers/NoticeController.php
<?php

namespace App\Http\Controllers;

use App\Batch;
use App\Notice;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

class NoticeController extends Controller
{
    const VIEW_PATH = 'authority.notices.';
    const FILE_PATH = 'public/notices/';

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $notices = Notice::latest()->get();

        return view(self::VIEW_PATH. 'index', compact('notices'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        $batches = Batch::where('status', 1)->latest()->get();

        $notice = new Notice();

        return view(self::VIEW_PATH .'edit', compact('batches','notice'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $input = $request->except('_token');

        $this->validator($input)->validate();


        try {
            DB::beginTransaction();

            $input['attachment'] = md5(microtime()) . '.' . $request->file('attachment')->extension();

            $notice = Notice::create($input);

            Storage::putFileAs(
                self::FILE_PATH,
                $request->file('attachment'),
                $notice->attachment
            );
            DB::commit();
        } catch (\Throwable $exception) {
            Log::debug($exception->getMessage());
            DB::rollBack();
            return back()
                ->with(["error" => "Something Wrong. Please Try Again"])
                ->withInput();
        }

        return back()->with(["success" => "Notice Successfully Created"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  Notice  $notice
     * @return Factory|View
     */
    public function show(Notice $notice)
    {
        return view(self::VIEW_PATH .'view', compact('notice'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Notice  $notice
     * @return Factory|View
     */
    public function edit(Notice $notice)
    {
        $batches = Batch::where('status', 1)->latest()->get();

        return view(self::VIEW_PATH .'edit', compact('notice', 'batches'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  Notice  $notice
     * @return RedirectResponse
     */
    public function update(Request $request, Notice $notice)
    {
        $input = $request->except('_token');

        $this->validator($input, true)->validate();

        try {
            DB::beginTransaction();

            if ($request->hasFile('attachment')) {

                $input['attachment'] = md5(microtime()) . '.' . $request->file('attachment')->extension();

                if($notice->attachment && Storage::exists(self::FILE_PATH . $notice->attachment)) {
                    Storage::delete(self::FILE_PATH . $notice->attachment);
                }

                Storage::putFileAs(
                    self::FILE_PATH,
                    $request->file('attachment'),
                    $input['attachment']
                );
            }

            $notice->update($input);

            DB::commit();
        } catch (\Throwable $exception) {
            Log::debug($exception->getMessage());
            DB::rollBack();
            return back()
                ->with(["error" => "Something Wrong. Please Try Again"])
                ->withInput();
        }

        return back()->with(["success" => "Notice Successfully Updated"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Notice  $notice
     * @return RedirectResponse
     */
    public function destroy(Notice $notice)
    {
        try {
            if($notice->attachment && Storage::exists(self::FILE_PATH . $notice->attachment)) {
                Storage::delete(self::FILE_PATH . $notice->attachment);
            }
            $notice->delete();
        } catch (\Throwable $exception) {
            return redirect()->route('admin.notices.index')
                ->with(["error" => "Something Wrong. Please Try Again"]);
        }
        return redirect()->route('admin.notices.index')
            ->with(["success" => "Notice Successfully Deleted"]);
    }

    public function validator(array $data, $edit=false)
    {
        $rule = [
            'title' => ['required', 'string', 'max:255'],
            'attachment' => 'required|mimes:pdf',
            "type" => "required",
            "batch_id" => "required"
        ];
        if ($edit) {
            unset($rule['attachment']);
        }
        return Validator::make($data, $rule, []);
    }
}

resources/views/authority/notices/edit.blade.php
@extends('layouts.back')

@php
    $edit = isset($notice->id) && !empty($notice->id);
@endphp
{{--                    'batch_id', 'type', 'priority', 'title', 'content', 'attachment', 'status'--}}

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <!-- /.col-->
            <div class="col-sm-12">
                @include('notifications.message')
                <div class="card card-accent-info">
                    <div class="card-header">
                        <h5>
                            <strong>Notice</strong>
                            <small>{{$edit ? 'Edit' : 'Add'}}</small>
                        </h5>
                    </div>
                    <form method="post"
                          action="{{$edit ? route('admin.notices.update', $notice->id) : route('admin.notices.store')}}"
                          enctype="multipart/form-data">
                        @csrf
                        @if($edit)
                            @method('put')
                        @endif

                        <div class="card-body">
                            <div class="row">
                                @can('viewAny', \App\User::class)
                                    <div class="form-group col-md-6">
                                        <label for="batch_id">Select Batch</label>
                                        <select class="form-control
                                            @error('batch_id') is-invalid @enderror"
                                                id="batch_id" name="batch_id">
                                            @foreach($batches as $batch)
                                                <option value="{{$batch->id}}"
                                                        {{old('batch_id', $edit ? $notice->batch_id : 0) == $batch->id ? 'selected' : ''}}>
                                                    {{$batch->batch_name . '('. $batch->course_title . ')'}}
                                                </option>
                                            @endforeach
                                        </select>
                                        @error('batch_id')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                @else
                                    <input type="hidden" value="{{auth()->user()->batch_id}}" name="batch_id" />
                                @endcan

                                <div class="form-group col-md-6">
                                    <label for="type">Notice About</label>
                                    <select class="form-control  @error('type') is-invalid @enderror" name="type">
                                        <option selected disabled>Select Notice Type</option>
                                        <option value="class"{{old('type', $notice->type) === 'class' ? 'selected' : ''}}>Class</option>
                                        <option value="exam"{{old('type', $notice->type) === 'exam' ? 'selected' : ''}}>Exam</option>
                                        <option value="others"{{old('type', $notice->type) === 'others' ? 'selected' : ''}}>Others</option>
                                    </select>
                                    @error('type')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-12">
                                    <label for="content">Details</label>
                                    <textarea class="form-control" id="content" name="content">{{$edit ? $notice->content : ''}}</textarea>
                                </div>

                                <div class="form-group col-md-6">
                                    <label for="title">Title</label>
                                    <input class="form-control  @error('title') is-invalid @enderror" type="text"
                                           name="title" value="{{old('title', $notice->title)}}"/>
                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-6">
                                    <div class="clearfix"></div>
                                    <label for="attachment">Attachment PDF (<span class="pdf-name">{{$edit ? $notice->attachment : 'Empty'}}</span>)</label>
                                    <div class="custom-file">
                                        <input onchange="loadFile(event)" type="file" name="attachment" accept="application/pdf"
                                               class="custom-file-input  @error('attachment') is-invalid @enderror"
                                               id="customFile">
                                        <label class="custom-file-label" for="customFile">Choose PDFs</label>
                                    </div>
                                    @error('attachment')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                        </div>

                        <div class="card-footer">
                            <a class="btn btn-sm btn-danger" href="{{ url()->previous() }}">
                                <i class="fa fa-dot-circle-o"></i> Cancel</a>
                            <button class="btn btn-sm btn-primary" type="submit">
                                <i class="fa fa-dot-circle-o"></i> {{$edit ? 'Save Change' : 'Add Notice' }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.col-->
        </div>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">
        var loadFile = function (event) {
            $('.pdf-name').text(event.target.files[0].name);
        };
    </script>
@endpush

resources/views/authority/notices/index.blade.php
@extends('layouts.back')

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                @include('notifications.message')
                <div class="card card-accent-dark">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i> Notices

                        <div class="card-header-actions btn-group btn-group-sm">
                            <a href="{{route('admin.notices.create')}}"
                               class="card-header-action btn btn-outline-dark">
                                Add New
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="datatable table table-striped">
                            <thead>
                            <tr>
                                <th>Type</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>attachment</th>
                                <th>status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($notices as $notice)
                                <tr>
                                    <td>{{$notice->type}}</td>
                                    <td>{{$notice->title}}</td>
                                    <td>{{$notice->content}}</td>
                                    <td>
                                        <a target="_blank" href="{{asset('storage/notices/'.$notice->attachment)}}">
                                            <i class="fa fa-download"></i>
                                        </a>
                                    </td>
                                    <td>{{$notice->status}}</td>
                                    <td>
                                        <div class="btn-group btn-group-sm" role="group">
                                            <a
                                                data-toggle="tooltip"
                                                title="View This Company"
                                                href="{{route('admin.notices.show', $notice->id)}}"
                                                class="btn btn-outline-info">
                                                <i class="fa fa-eye" aria-hidden="true"></i>
                                            </a>
                                            <a
                                                data-toggle="tooltip"
                                                title="Edit This Company"
                                                href="{{route('admin.notices.edit', $notice->id)}}"
                                                class="btn btn-outline-warning">
                                                <i class="fa fa-edit" aria-hidden="true"></i>
                                            </a>
                                            <button
                                                data-toggle="tooltip"
                                                title="Delete This Company"
                                                onclick="ConfirmDelete('deleteForm_'+'{{$notice->id}}');" type="button"
                                                class="card-header-action btn btn-outline-danger">
                                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                                            </button>
                                            <form id="deleteForm_{{$notice->id}}"
                                                  action="{{route('admin.notices.destroy', $notice->id)}}"
                                                  method="post">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4">Empty table</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.col-->
        </div>
    </div>


    <!-- Modal -->
    <div class="modal" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Please Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h2>Are You Sure?</h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button onclick="document.getElementById(elm_to_delete).submit();" type="button"
                            class="btn btn-danger">Confirm
                    </button>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        var elm_to_delete;

        function ConfirmDelete(elm = null) {
            elm_to_delete = elm;
            $("#confirm-delete").modal('show');
        }

        $(function () {
            $('.datatable').DataTable();
        });
    </script>
@endpush

resources/views/authority/notices/view.blade.php
@extends('layouts.back')

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                @include('notifications.message')
                <div class="card card-accent-primary">
                    <div class="card-header">
                        {{$notice->title}}
                        <div class="card-header-actions btn-group btn-group-sm">
                            <a href="{{route('admin.notices.edit', $notice->id)}}" class="card-header-action btn btn-outline-warning">
                                <i class="fa fa-edit" aria-hidden="true"></i>
                            </a>
                            <button data-toggle="modal" data-target="#confirm-delete"  type="button" class="card-header-action btn btn-outline-danger">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                            <form id="deleteForm" action="{{route('admin.notices.destroy', $notice->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                            </form>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-9">
                                <h3 class="card-title">Notice Details</h3>

                                <table class="table">
                                    <tr>
                                        <th>Notice Title:</th>
                                        <td>{{$notice->title}}</td>
                                    </tr>
                                    <tr>
                                        <th>Notice About</th>
                                        <td>{{$notice->type}}</td>
                                    </tr>
                                    <tr>
                                        <th>Notice For Batch</th>
                                        <td>{{$notice->batch->batch_name}}</td>
                                    </tr>
                                    <tr>
                                        <th>Description</th>
                                        <td>{{$notice->content}}</td>
                                    </tr>
                                    <tr>
                                        <th>Attachment PDF</th>
                                        <td>
                                            <a href="{{asset('storage/notices/'.$notice->attachment)}}" target="_blank">
                                                <i class="fa fa-download"></i> View
                                            </a>
                                        </td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Please Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h2>Are You Sure?</h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button onclick="document.getElementById('deleteForm').submit();" type="button" class="btn btn-danger">Confirm</button>
                </div>
            </div>
        </div>
    </div>
@endsection