routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/register', function (){
   return redirect('/login');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function(){
    Route::resource('students', 'StudentController');
    Route::resource('authorities', 'AuthorityController');
    Route::resource('notices', 'NoticeController');
    Route::resource('batches', 'BatchController');
});

app/Batch.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Batch extends Model
{
    protected $fillable = ['batch_name', 'session', 'course_title', 'status'];

    public function users()
    {
        return $this->hasMany(User::class);
    }

    public function students()
    {
        return $this->users()->students();
    }

    public function notices()
    {
        return $this->hasMany(Notice::class);
    }
}

app/Http/Controllers/AuthorityController.php
<?php

namespace App\Http\Controllers;

use App\Batch;
use App\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

class AuthorityController extends Controller
{
    const IMAGE_PATH = 'public/students/';
    const VIEW_PATH = 'authority.authorities.';

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $authorities = User::where('role', '!=', User::ROLE_STUDENT)->get();

        return view(self::VIEW_PATH.'index', compact('authorities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $batches = Batch::where('status', 1)->latest()->get();

        $authority = new User();

        $this->authorize('viewAny', $authority);

        $roles = [
          User::ROLE_CR => 'CR',
          User::ROLE_TEACHER => 'Teacher',
          User::ROLE_STAFF => 'Staff',
        ];

        return view(self::VIEW_PATH.'edit', compact('batches', 'authority', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $input = $request->except('_token');

        $this->validator($input)->validate();

        try {
            DB::beginTransaction();
            $input['image'] = md5(microtime()).'.'.$request->file('image')->extension();
            $input['password'] = Hash::make(strlen($input['password']) ? $input['password'] : '123456');

            $authority = User::create($input);

            Storage::putFileAs(
                self::IMAGE_PATH,
                $request->file('image'),
                $authority->image
            );
            DB::commit();

        } catch (\Throwable $exception) {
            Log::debug($exception->getMessage());
            DB::rollBack();
            return back()
                ->with(["error" => "Something Wrong. Please Try Again"])
                ->withInput();
        }

        return back()->with(["success" => "Authority Successfully Created"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Factory|View
     * @throws \Exception
     */
    public function show($id)
    {
        $authority = User::findOrFail($id);

        $this->authorize('viewAny', $authority);

        return view(self::VIEW_PATH.'view', compact('authority'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Factory|View
     * @throws \Exception
     */
    public function edit($id)
    {
        $authority = User::findOrFail($id);

        $this->authorize('viewAny', $authority);

        $batches = Batch::where('status', 1)->latest()->get();

        $roles = [
            User::ROLE_CR => 'CR',
            User::ROLE_TEACHER => 'Teacher',
            User::ROLE_STAFF => 'Staff',
        ];

        return view(self::VIEW_PATH.'edit', compact('authority', 'batches', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(Request $request, $id)
    {
        $authority = User::findOrFail($id);

        $input = $request->except('_token');

        $this->validator($input, $id)->validate();

        try {
            DB::beginTransaction();

            if (strlen($request->post('password'))) {
                $input['password'] = Hash::make($input['password']);
            } else {
                unset($input['password']);
            }

            if ($request->hasFile('image')) {
                $input['image'] = md5(microtime()).'.'.$request->file('image')->extension();

                if ($authority->image && Storage::exists(self::IMAGE_PATH.$authority->image)) {
                    Storage::delete(self::IMAGE_PATH.$authority->image);
                }

                Storage::putFileAs(
                    self::IMAGE_PATH,
                    $request->file('image'),
                    $input['image']
                );
            }
            if ($request->has('image_status') && $request->post('image_status') < 1) {
                $input['image'] = null;
                Storage::delete(self::IMAGE_PATH.$authority->image);
            }

            $authority->update($input);

            DB::commit();
        } catch (\Throwable $exception) {
            Log::debug($exception->getMessage());
            DB::rollBack();
            return back()
                ->with(["error" => "Something Wrong. Please Try Again"])
                ->withInput();
        }

        return back()->with(["success" => "Authority Successfully Updated"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $authority = User::findOrFail($id);

        $this->authorize('viewAny', $authority);

        try {
            if ($authority->image && Storage::exists(self::IMAGE_PATH.$authority->image)) {
                Storage::delete(self::IMAGE_PATH.$authority->image);
            }
            $authority->delete();
        } catch (\Throwable $exception) {
            return redirect()->route('admin.authorities.index')
                ->with(["error" => "Something Wrong. Please Try Again"]);
        }
        return redirect()->route('admin.authorities.index')
            ->with(["success" => "Authority Successfully Created"]);
    }

    public function validator(array $data, $id = null)
    {
        $rule = [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,'.$id],
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            "gender" => "required",
            "role" => "required"
        ];
        return Validator::make($data, $rule, []);
    }
}

app/Http/Controllers/BatchController.php
<?php

namespace App\Http\Controllers;

use App\Batch;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

class BatchController extends Controller
{
    const VIEW_PATH = 'authority.batches.';
    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $batches = Batch::latest()->get();

        return view(self::VIEW_PATH. 'index', compact('batches'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     */
    public function create()
    {
        $batch = new Batch();

        return view(self::VIEW_PATH .'edit', compact('batch'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $input = $request->except('_token');

        $this->validator($input)->validate();

        try {
            $batch = Batch::create($input);
        } catch (\Throwable $exception) {
            Log::debug($exception->getMessage());
            return back()
                ->with(["error" => "Something Wrong. Please Try Again"])
                ->withInput();
        }

        return back()->with(["success" => "Batch Successfully Created"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  Batch  $batch
     * @return Factory|View
     */
    public function show(Batch $batch)
    {
        return view(self::VIEW_PATH .'view', compact('batch'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Batch  $batch
     * @return Factory|View
     */
    public function edit(Batch $batch)
    {
        return view(self::VIEW_PATH .'edit', compact( 'batch'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  Batch  $batch
     * @return RedirectResponse
     */
    public function update(Request $request, Batch $batch)
    {
        $input = $request->except('_token');

        $this->validator($input)->validate();

        try {
            $batch->update($input);
        } catch (\Throwable $exception) {
            Log::debug($exception->getMessage());
            return back()
                ->with(["error" => "Something Wrong. Please Try Again"])
                ->withInput();
        }

        return back()->with(["success" => "Batch Successfully Created"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Batch  $batch
     * @return RedirectResponse
     */
    public function destroy(Batch $batch)
    {
        try {
            $batch->delete();
        } catch (\Throwable $exception) {
            return redirect()->route('admin.batches.index')
                ->with(["error" => "Something Wrong. Please Try Again"]);
        }
        return redirect()->route('admin.batches.index')
            ->with(["success" => "Student Successfully Updated"]);
    }

    public function validator(array $data, $id=null)
    {
        $rule = [
            'batch_name' => ['required'],
            'session' => ['required'],
            'course_title' => ['required'],
        ];
        return Validator::make($data, $rule, [
            'batch_name.required' => 'Batch Required'
        ]);
    }
}

resources/views/authority/batches/edit.blade.php
@extends('layouts.back')

@php
    $edit = isset($batch->id) && !empty($batch->id);
@endphp

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <!-- /.col-->
            <div class="col-sm-12">
                @include('notifications.message')
                <div class="card card-accent-info">
                    <div class="card-header">
                        <h5>
                            <strong>Batch</strong>
                            <small>{{$edit ? 'Edit' : 'Add'}}</small>
                        </h5>
                    </div>
                    <form method="post"
                          action="{{$edit ? route('admin.batches.update', $batch->id) : route('admin.batches.store')}}"
                          enctype="multipart/form-data">
                        @csrf
                        @if($edit)
                            @method('put')
                        @endif

                        <div class="card-body">
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label for="batch_name">Batch No</label>
                                    <input type="text" name="batch_name" value="{{$edit ? $batch->batch_name : ''}}"
                                           class="form-control @error('batch_name') is-invalid @enderror">
                                    @error('batch_name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-6">
                                    <label for="session">Session</label>
                                    <input type="text" name="session" value="{{$edit ? $batch->session : ''}}"
                                           class="form-control @error('session') is-invalid @enderror">
                                    @error('session')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-6">
                                    <label for="session">Course Title</label>
                                    <input type="text" name="course_title" value="{{$edit ? $batch->course_title : ''}}"
                                           class="form-control @error('course_title') is-invalid @enderror">
                                    @error('course_title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                @if($edit)
                                    <div class="form-group col-md-6">
                                        <label for="status">Status</label>
                                        <select type="text" name="status"
                                                class="form-control @error('status') is-invalid @enderror">
                                            <option value="active" {{$batch->status === 'active' ? 'selected': ''}}>Active</option>
                                            <option value="inactive" {{$batch->status === 'inactive' ? 'selected': ''}}>Inactive</option>
                                        </select>
                                        @error('status')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                @endif
                            </div>
                        </div>

                        <div class="card-footer">
                            <a class="btn btn-sm btn-danger" href="{{ url()->previous() }}">
                                <i class="fa fa-dot-circle-o"></i> Cancel</a>
                            <button class="btn btn-sm btn-primary" type="submit">
                                <i class="fa fa-dot-circle-o"></i> {{$edit ? 'Save Change' : 'Add Batch' }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.col-->
        </div>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">
        var loadFile = function (event) {
            $('.pdf-name').text(event.target.files[0].name);
        };
    </script>
@endpush

resources/views/authority/batches/index.blade.php
@extends('layouts.back')

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                @include('notifications.message')
                <div class="card card-accent-dark">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i> Batches

                        <div class="card-header-actions btn-group btn-group-sm">
                            <a href="{{route('admin.batches.create')}}"
                               class="card-header-action btn btn-outline-dark">
                                Add New
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="datatable table table-striped">
                            <thead>
                            <tr>
                                <th>Batch</th>
                                <th>Session</th>
                                <th>Title</th>
                                <th>Total Student</th>
                                <th>status</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($batches as $batch)
                                <tr>
                                    <td>{{$batch->batch_name}}</td>
                                    <td>{{$batch->session}}</td>
                                    <td>{{$batch->course_title}}</td>
                                    <td>{{$batch->students()->count()}}</td>
                                    <td>{{$batch->status}}</td>
                                    <td>
                                        <div class="btn-group btn-group-sm" role="group">
                                            <a
                                                data-toggle="tooltip"
                                                title="View This Company"
                                                href="{{route('admin.batches.show', $batch->id)}}"
                                                class="btn btn-outline-info">
                                                <i class="fa fa-eye" aria-hidden="true"></i>
                                            </a>
                                            <a
                                                data-toggle="tooltip"
                                                title="Edit This Company"
                                                href="{{route('admin.batches.edit', $batch->id)}}"
                                                class="btn btn-outline-warning">
                                                <i class="fa fa-edit" aria-hidden="true"></i>
                                            </a>
                                            <button
                                                data-toggle="tooltip"
                                                title="Delete This Company"
                                                onclick="ConfirmDelete('deleteForm_'+'{{$batch->id}}');" type="button"
                                                class="card-header-action btn btn-outline-danger">
                                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                                            </button>
                                            <form id="deleteForm_{{$batch->id}}"
                                                  action="{{route('admin.batches.destroy', $batch->id)}}"
                                                  method="post">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4">Empty table</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.col-->
        </div>
    </div>


    <!-- Modal -->
    <div class="modal" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Please Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h2>Are You Sure?</h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button onclick="document.getElementById(elm_to_delete).submit();" type="button"
                            class="btn btn-danger">Confirm
                    </button>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        var elm_to_delete;

        function ConfirmDelete(elm = null) {
            elm_to_delete = elm;
            $("#confirm-delete").modal('show');
        }

        $(function () {
            $('.datatable').DataTable();
        });
    </script>
@endpush

resources/views/authority/batches/view.blade.php
@extends('layouts.back')

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                @include('notifications.message')
                <div class="card card-accent-primary">
                    <div class="card-header">
                        {{$batch->batch_name . ' ('. $batch->course_title . ')' }}
                        <div class="card-header-actions btn-group btn-group-sm">
                            <a href="{{route('admin.notices.edit', $batch->id)}}" class="card-header-action btn btn-outline-warning">
                                <i class="fa fa-edit" aria-hidden="true"></i>
                            </a>
                            <button data-toggle="modal" data-target="#confirm-delete"  type="button" class="card-header-action btn btn-outline-danger">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                            <form id="deleteForm" action="{{route('admin.notices.destroy', $batch->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                            </form>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-9">
                                <h3 class="card-title">Notice Details</h3>
                                <table class="table">
                                    <tr>
                                        <th>Batch:</th>
                                        <td>{{$batch->batch_name}}</td>
                                    </tr>
                                    <tr>
                                        <th>Session</th>
                                        <td>{{$batch->session}}</td>
                                    </tr>
                                    <tr>
                                        <th>Course Name</th>
                                        <td>{{$batch->course_title}}</td>
                                    </tr>
                                    <tr>
                                        <th>Total Student</th>
                                        <td>{{$batch->students()->count()}}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Please Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h2>Are You Sure?</h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button onclick="document.getElementById('deleteForm').submit();" type="button" class="btn btn-danger">Confirm</button>
                </div>
            </div>
        </div>
    </div>
@endsection