routes/web.php
<?php
use Illuminate\Support\Facades\Route;

Auth::routes();

Route::get('/', function () {
    return redirect('/login');
});

Route::get('/register', function (){
   return redirect('/login');
});

Route::get('/home', 'HomeController@index')->name('home');


Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth'], function(){
    Route::resource('students', 'StudentController');
    Route::resource('authorities', 'AuthorityController');
    Route::resource('notices', 'NoticeController');
    Route::resource('batches', 'BatchController');
});

app/Http/Controllers/AuthorityController.php
<?php

namespace App\Http\Controllers;

use App\Batch;
use App\User;
use Illuminate\Contracts\View\Factory;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Facades\Validator;
use Illuminate\View\View;

class AuthorityController extends Controller
{
    const IMAGE_PATH = 'public/students/';
    const VIEW_PATH = 'authority.authorities.';

    /**
     * Display a listing of the resource.
     *
     * @return Factory|View
     */
    public function index()
    {
        $authorities = User::where('role', '!=', User::ROLE_STUDENT)->get();

        return view(self::VIEW_PATH.'index', compact('authorities'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Factory|View
     * @throws \Illuminate\Auth\Access\AuthorizationException
     */
    public function create()
    {
        $batches = Batch::where('status', 1)->latest()->get();

        $authority = new User();

        $this->authorize('viewAny', $authority);

        $roles = [
          User::ROLE_CR => 'CR',
          User::ROLE_TEACHER => 'Teacher',
          User::ROLE_STAFF => 'Staff',
        ];

        return view(self::VIEW_PATH.'edit', compact('batches', 'authority', 'roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  Request  $request
     * @return RedirectResponse
     */
    public function store(Request $request)
    {
        $input = $request->except('_token');

        $this->validator($input)->validate();

        try {
            DB::beginTransaction();
            $input['image'] = md5(microtime()).'.'.$request->file('image')->extension();
            $input['password'] = Hash::make(strlen($input['password']) ? $input['password'] : '123456');

            $authority = User::create($input);

            Storage::putFileAs(
                self::IMAGE_PATH,
                $request->file('image'),
                $authority->image
            );
            DB::commit();

        } catch (\Throwable $exception) {
            Log::debug($exception->getMessage());
            DB::rollBack();
            return back()
                ->with(["error" => "Something Wrong. Please Try Again"])
                ->withInput();
        }

        return back()->with(["success" => "Authority Successfully Created"]);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return Factory|View
     * @throws \Exception
     */
    public function show($id)
    {
        $authority = User::findOrFail($id);

        $this->authorize('viewAny', $authority);

        return view(self::VIEW_PATH.'view', compact('authority'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Factory|View
     * @throws \Exception
     */
    public function edit($id)
    {
        $authority = User::findOrFail($id);

        $this->authorize('viewAny', $authority);

        $batches = Batch::where('status', 1)->latest()->get();

        $roles = [
            User::ROLE_CR => 'CR',
            User::ROLE_TEACHER => 'Teacher',
            User::ROLE_STAFF => 'Staff',
        ];

        return view(self::VIEW_PATH.'edit', compact('authority', 'batches', 'roles'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  Request  $request
     * @param  int  $id
     * @return RedirectResponse
     * @throws \Exception
     */
    public function update(Request $request, $id)
    {
        $authority = User::findOrFail($id);

        $input = $request->except('_token');

        $this->validator($input, $id)->validate();

        try {
            DB::beginTransaction();

            if (strlen($request->post('password'))) {
                $input['password'] = Hash::make($input['password']);
            } else {
                unset($input['password']);
            }

            if ($request->hasFile('image')) {
                $input['image'] = md5(microtime()).'.'.$request->file('image')->extension();

                if ($authority->image && Storage::exists(self::IMAGE_PATH.$authority->image)) {
                    Storage::delete(self::IMAGE_PATH.$authority->image);
                }

                Storage::putFileAs(
                    self::IMAGE_PATH,
                    $request->file('image'),
                    $input['image']
                );
            }
            if ($request->has('image_status') && $request->post('image_status') < 1) {
                $input['image'] = null;
                Storage::delete(self::IMAGE_PATH.$authority->image);
            }

            $authority->update($input);

            DB::commit();
        } catch (\Throwable $exception) {
            Log::debug($exception->getMessage());
            DB::rollBack();
            return back()
                ->with(["error" => "Something Wrong. Please Try Again"])
                ->withInput();
        }

        return back()->with(["success" => "Authority Successfully Updated"]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return RedirectResponse
     * @throws \Exception
     */
    public function destroy($id)
    {
        $authority = User::findOrFail($id);

        $this->authorize('viewAny', $authority);

        try {
            if ($authority->image && Storage::exists(self::IMAGE_PATH.$authority->image)) {
                Storage::delete(self::IMAGE_PATH.$authority->image);
            }
            $authority->delete();
        } catch (\Throwable $exception) {
            return redirect()->route('admin.authorities.index')
                ->with(["error" => "Something Wrong. Please Try Again"]);
        }
        return redirect()->route('admin.authorities.index')
            ->with(["success" => "Authority Successfully Created"]);
    }

    public function validator(array $data, $id = null)
    {
        $rule = [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email,'.$id],
            'image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            "gender" => "required",
            "role" => "required"
        ];
        return Validator::make($data, $rule, []);
    }
}

resources/views/authority/authorities/edit.blade.php
@extends('layouts.back')

@php
    $edit = isset($authority->id) && !empty($authority->id);
@endphp

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <!-- /.col-->
            <div class="col-sm-12">
                @include('notifications.message')
                <div class="card card-accent-info">
                    <div class="card-header">
                        <h5>
                            <strong>Authority</strong>
                            <small>{{$edit ? 'Edit' : 'Add'}}</small>
                        </h5>
                    </div>
                    <form method="post"
                          action="{{$edit ? route('admin.authorities.update', $authority->id) : route('admin.authorities.store')}}"
                          enctype="multipart/form-data">
                        @csrf
                        @if($edit)
                            @method('put')
                        @endif

                        <div class="card-body">
                            <div class="row">
                                <div class="form-group col-md-6">
                                    <label for="role">Select Role</label>
                                    <select class="form-control
                                            @error('role') is-invalid @enderror"
                                            id="role" name="role">
                                        <option selected value="">Select Role</option>
                                        @foreach($roles as $key => $role)
                                            <option value="{{$key}}"
                                                    {{old('role', $edit ? $authority->role : '') == $key ? 'selected' : ''}}>
                                                {{$role}}
                                            </option>
                                        @endforeach
                                    </select>
                                    @error('role')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-6">
                                    <label for="name">Name</label>
                                    <input class="form-control  @error('name') is-invalid @enderror" type="text"
                                           name="name" value="{{old('name', $authority->name)}}"/>
                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-6">
                                    <label for="email">Email</label>
                                    <input class="form-control  @error('email') is-invalid @enderror" type="email"
                                           name="email" value="{{old('email', $authority->email)}}"/>
                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                @if(!$edit || auth()->user()->id == $authority->id)
                                    <div class="form-group col-md-6">
                                        <label for="password">Password (Default: 123456)</label>
                                        <input class="form-control  @error('password') is-invalid @enderror"
                                               type="password"
                                               name="password" value="{{$edit ? '': '123456'}}"/>
                                        @error('password')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                @endif

                                <div class="form-group col-md-6">
                                    <label for="gender">Gender</label>
                                    <select class="form-control  @error('gender') is-invalid @enderror" name="gender">
                                        <option selected disabled>Select Gender</option>
                                        <option
                                                value="Male"
                                                {{old('gender', $authority->gender) === 'Male' ? 'selected' : ''}}>Male
                                        </option>
                                        <option
                                                value="Female"
                                                {{old('gender', $authority->gender) === 'Female' ? 'selected' : ''}}>
                                            Female
                                        </option>
                                    </select>
                                    @error('gender')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>

                                <div class="form-group col-md-6">
                                    @if($authority->image)
                                        <img id="image_output" style="width: 100px"
                                             src="{{asset('storage/students/'.$authority->image)}}"/>
                                        <button type="button" class="remove-image btn btn-sm btn-danger">
                                            <i class="fa fa-trash-o"></i>
                                        </button>
                                    @else
                                        <img id="image_output" style="width: 80px" src="{{url('/')}}/assets/blank.png"/>
                                    @endif
                                    <div class="clearfix"></div>
                                    <label for="image">Profile Image</label>
                                    <div class="custom-file">
                                        <input onchange="loadFile(event)" type="file" accept="image/*" name="image"
                                               class="custom-file-input  @error('image') is-invalid @enderror"
                                               id="customFile">
                                        <label class="custom-file-label" for="customFile">Choose Image</label>
                                    </div>
                                    @error('image')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                    <input type="hidden" name="image_status" id="image_status" value="1"/>
                                </div>
                            </div>
                        </div>

                        <div class="card-footer">
                            <a class="btn btn-sm btn-danger" href="{{ url()->previous() }}">
                                <i class="fa fa-dot-circle-o"></i> Cancel</a>
                            <button class="btn btn-sm btn-primary" type="submit">
                                <i class="fa fa-dot-circle-o"></i> {{$edit ? 'Save Change' : 'Add Authority' }}
                            </button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- /.col-->
        </div>
    </div>
@endsection

@push('scripts')
    <script type="text/javascript">
        var loadFile = function (event) {
            $("#image_output").attr('src', URL.createObjectURL(event.target.files[0]));
            if ($("#image_output").is(':hidden')) {
                $("#image_output").show(300);
                $(".remove-image").show(300);
            }
            $('#image_status').val(1);
        };

        $(function () {
            $('.remove-image').on('click', function () {
                $('#image_output').hide(300);
                $(this).hide(300);
                $('#image_status').val(0);
            });

            $('#dob').flatpickr({
                enableTime: false,
                dateFormat: "Y-m-d",
                enable: [
                    {
                        from: "1990-01-01",
                        // to: new Date()
                        to: "{{(new \DateTime())->modify('-18 years')->format('Y-m-d')}}"
                    }
                ]
            });
        })

    </script>
@endpush

resources/views/authority/authorities/index.blade.php
@extends('layouts.back')

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-lg-12 col-md-12">
                @include('notifications.message')
                <div class="card card-accent-dark">
                    <div class="card-header">
                        <i class="fa fa-align-justify"></i>Authority lists

                        <div class="card-header-actions btn-group btn-group-sm">
                            <a href="{{route('admin.authorities.create')}}"
                               class="card-header-action btn btn-outline-dark">
                                Add New
                            </a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="datatable table table-striped">
                            <thead>
                            <tr>
                                <th>Batch</th>
                                <th>Name</th>
                                <th>Role</th>
                                <th>Email</th>
                                <th>Gender</th>
                                <th>Action</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($authorities as $authority)
                                <tr>
                                    <td>{{optional($authority->batch)->batch_name }}</td>
                                    <td>{{$authority->name}}</td>
                                    <td>{{\Illuminate\Support\Str::ucfirst($authority->role)}}</td>
                                    <td>{{$authority->email}}</td>
                                    <td>{{$authority->gender}}</td>
                                    <td>
                                        <div class="btn-group btn-group-sm" role="group">
                                            <a
                                                data-toggle="tooltip"
                                                title="View This Authority"
                                                href="{{route('admin.authorities.show', $authority->id)}}"
                                                class="btn btn-outline-info">
                                                <i class="fa fa-eye" aria-hidden="true"></i>
                                            </a>
                                            <a
                                                data-toggle="tooltip"
                                                title="Edit This Authority"
                                                href="{{route('admin.authorities.edit', $authority->id)}}"
                                                class="btn btn-outline-warning">
                                                <i class="fa fa-edit" aria-hidden="true"></i>
                                            </a>
                                            <button
                                                data-toggle="tooltip"
                                                title="Delete This Authority"
                                                onclick="ConfirmDelete('deleteForm_'+'{{$authority->id}}');" type="button"
                                                class="card-header-action btn btn-outline-danger">
                                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                                            </button>
                                            <form id="deleteForm_{{$authority->id}}"
                                                  action="{{route('admin.authorities.destroy', $authority->id)}}"
                                                  method="post">
                                                @csrf
                                                @method('DELETE')
                                            </form>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="4">Empty table</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <!-- /.col-->
        </div>
    </div>


    <!-- Modal -->
    <div class="modal" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Please Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h2>Are You Sure?</h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button onclick="document.getElementById(elm_to_delete).submit();" type="button"
                            class="btn btn-danger">Confirm
                    </button>
                </div>
            </div>
        </div>
    </div>
@endsection

@push('scripts')
    <script>
        var elm_to_delete;

        function ConfirmDelete(elm = null) {
            elm_to_delete = elm;
            $("#confirm-delete").modal('show');
        }

        $(function () {
            $('.datatable').DataTable();
        });
    </script>
@endpush

resources/views/authority/authorities/view.blade.php
@extends('layouts.back')

@section('content')
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                @include('notifications.message')
                <div class="card card-accent-primary">
                    <div class="card-header">
                        {{$authority->name}}
                        <div class="card-header-actions btn-group btn-group-sm">
                            <a href="{{route('admin.authorities.edit', $authority->id)}}" class="card-header-action btn btn-outline-warning">
                                <i class="fa fa-edit" aria-hidden="true"></i>
                            </a>
                            <button data-toggle="modal" data-target="#confirm-delete"  type="button" class="card-header-action btn btn-outline-danger">
                                <i class="fa fa-trash-o" aria-hidden="true"></i>
                            </button>
                            <form id="deleteForm" action="{{route('admin.authorities.destroy', $authority->id)}}" method="post">
                                @csrf
                                @method('DELETE')
                            </form>
                        </div>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                                @if($authority->image)
                                    <img style="width: 100%" src="{{asset('storage/students/' .$authority->image)}}"/>
                                @else
                                    <img id="logo_output" style="width: 80px" src="{{url('/')}}/assets/blank.png"/>
                                @endif
                            </div>
                            <div class="col-md-9">
                                <h3 class="card-title">Authority Profile</h3>

                                <table class="table">
                                    <tr>
                                        <th>Name:</th>
                                        <td>{{$authority->name}}</td>
                                    </tr>
                                    <tr>
                                        <th>Role</th>
                                        <td>{{\Illuminate\Support\Str::ucfirst($authority->role)}}</td>
                                    </tr>
                                    <tr>
                                        <th>Email</th>
                                        <td>{{$authority->email}}</td>
                                    </tr>
                                    <tr>
                                        <th>Gender</th>
                                        <td>{{$authority->gender}}</td>
                                    </tr>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Modal -->
    <div class="modal" id="confirm-delete" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Please Confirm</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <h2>Are You Sure?</h2>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                    <button onclick="document.getElementById('deleteForm').submit();" type="button" class="btn btn-danger">Confirm</button>
                </div>
            </div>
        </div>
    </div>
@endsection